extends:
    - airbnb
    - plugin:react/recommended

parser: babel-eslint

plugins:
    - react

rules:
    max-len:
      - 1
      - code: 150
    react/display-name: 0
    react/prop-types: 0
    react/jsx-no-bind: 1
    react/jsx-boolean-value: 0
    react/jsx-filename-extension: 0
    arrow-body-style: 0
    no-use-before-define: 0
    no-underscore-dangle: 0
    space-before-function-paren: 0
    spaced-comment: 0
    no-await-in-loop: 0
    no-constant-condition:
      - 2
      - checkLoops: false