const actionTypes = {
  SHOW_SPINNER: 'SHOW_SPINNER',
  SUCCESS_ADD_TODO: 'SUCCESS_ADD_TODO',
  FAILURE_ADD_TODO: 'FAILURE_ADD_TODO',
  SUCCESS_GET_TODO: 'SUCCESS_GET_TODO',
  FAILURE_GET_TODO: 'FAILURE_GET_TODO',
  SUCCESS_UPDATE_TODO: 'SUCCESS_UPDATE_TODO',
  FAILURE_UPDATE_TODO: 'FAILURE_UPDATE_TODO',
  SUCCESS_DELETE_TODO: 'SUCCESS_DELETE_TODO',
  FAILURE_DELETE_TODO: 'FAILURE_DELETE_TODO',
};

export default actionTypes;
